server:
  port: ${PORT:8000}
  
logging:
  level:
    root: DEBUG

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      # url: http://heroku-multiplication.herokuapp.com
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      # url: http://heroku-multiplication.herokuapp.com
      strip-prefix: false
    users:
      path: /users/**
      serviceId: multiplication
      # url: http://heroku-multiplication.herokuapp.com
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      # url: http://heroku-gamification.herokuapp.com
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      # url: http://heroku-gamification.herokuapp.com
      strip-prefix: false
    scores:
      path: /scores/**
      serviceId: gamification
      # url: http://heroku-gamification.herokuapp.com
      strip-prefix: false
    
management:
  endpoints:
    web:     
      exposure:
        include: "*"
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/
  instance:
    non-secure-port: 80
    hostname: ${DOMAIN_NAME}
    health-check-url: http://${DOMAIN_NAME}/actuator/health
    status-page-url: http://${DOMAIN_NAME}/actuator/info